os: linux
arch:
  - amd64
  - ppc64le
dist: bionic
sudo: false
language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy3"

matrix:
  exclude:
     - python: pypy3
       arch: ppc64le

install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install --editable .
script: py.test
after_success:
  - coveralls
cache: pip
